# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6d0a03545f7ec7bbc91f021fb0d0d6c5c330a56da9eb238c04650ad62496aad68e844b2086dea756578aa92ab615daa55d47d562a62f92db081dcc1badb5706

test:
  secret_key_base: 7e5f92aed14ad58ba2bce28a1bcf56191e4cfc0d0d2b1632b5aaa476af869d3f9bc92a4ff5a6f9d89f358202764c447e3b5dcaaad603b0a28f695c52edba1b2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
